// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('starter', ['ionic', 'ngCordova']).run(function($ionicPlatform) {
    return $ionicPlatform.ready(function() {
      if (window.cordova && window.cordova.plugins.Keyboard) {
        cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      }
      if (window.StatusBar) {
        return StatusBar.styleDefault();
      }
    });
  }).controller('testController', function($log, $scope, $cordovaBarcodeScanner, $cordovaDeviceOrientation, $ionicPlatform) {
    $scope.refreshHeading = function() {
      $log.debug("refreshHeading begin");
      $ionicPlatform.ready(function() {
        $log.debug("$ionicPlatform.ready begin");
        $cordovaDeviceOrientation.getCurrentHeading().then(function(result) {
          $log.debug("promise then");
          return $scope.heading = result;
        })["catch"](function(error) {
          $log.debug("promise catch");
          return $scope.error = error;
        });
        return $log.debug("$ionicPlatform.ready end");
      });
      return $log.debug("refreshHeading end");
    };
    $scope.refreshHeading();
    return $scope.scanBarcode = function() {
      $log.debug("scanBarcode begin");
      $ionicPlatform.ready(function() {
        $log.debug("$ionicPlatform.ready begin");
        $cordovaBarcodeScanner.scan().then(function(result) {
          $log.debug("promise then");
          return $scope.barcode = result;
        })["catch"](function(error) {
          $log.debug("promise catch");
          return $scope.error = error;
        });
        return $log.debug("$ionicPlatform.ready end");
      });
      return $log.debug("scanBarcode end");
    };
  });

}).call(this);

//# sourceMappingURL=app.js.map
